name: CI for Minikube

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Minikube
      run: |
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube /usr/local/bin/

    - name: Start Minikube
      run: |
        minikube start --driver=docker
        minikube status

    - name: Set up kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: Apply Kubernetes Deployment
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
        kubectl get deployments
        kubectl get pods

    - name: Expose Service
      run: |
        minikube service nginx-service --url
