name: CI for Minikube

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Minikube
      run: |
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube /usr/local/bin/

    - name: Start Minikube
      run: |
        minikube start --driver=docker
        minikube status

    - name: Set up kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: Apply Kubernetes Deployment
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
        kubectl get deployments
        kubectl get services
        kubectl get pods

    - name: List All Services
      run: |
        kubectl get svc --all-namespaces

    - name: Find Nginx Service Namespace
      id: find-namespace
      run: echo "::set-output name=namespace::$(kubectl get svc --all-namespaces | grep nginx-service | awk '{print $1}')"

    - name: Expose Service
      run: |
        namespace=$(echo "${{ steps.find-namespace.outputs.namespace }}")
        if [ -n "$namespace" ]; then
          minikube service nginx-service -n $namespace --url
        else
          echo "Nginx service not found in any namespace"
          exit 1
        fi
